### ISSUE TITLE
Catalina version - attached if you want it...

### ISSUE THREAD

**Issue by rogerfoxcroft** [gardockt/ch-merger#1]
There was not a Mac download, so as I have a dev machine set up I downloaded the project and created a Catalina binary. I've added it just in case you want to make this available to your users.

Couldn't see how else to message you about this. 👍 

R

[ch-merger.gz](https://github.com/gardockt/ch-merger/files/5179884/ch-merger.gz)

**Comment by gardockt** [comment]
Thank you for contributing! As I am currently unable to reliably compile and test future releases on Mac, I added your build to README as an unofficial build.
